on: push
jobs:
    build:
        runs-on: ubuntu-18.04
        steps:
            -   uses: actions/checkout@v2

            -   name: Deploy
                env:
                    SSH_AUTH_SOCK: /tmp/ssh_agent.sock
                run: |
                    mkdir -p ~/.ssh
                    echo "${{ secrets.SSH_HOST_KEY }}" >> ~/.ssh/known_hosts
                    ssh-agent -a $SSH_AUTH_SOCK > /dev/null
                    ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
                    echo "${{ secrets.SSH_TARGET }}" >> ~/.ssh/config
                    rsync src run.py static target:"${{ secrets.SSH_TARGET_DIR }}" -rv
